### ISSUE TITLE
Get units FX parameter

### ISSUE THREAD

**Issue by Erriez** [ReaTeam/ReaScripts-Templates#10]
The following script displays a list of alll FX parameters:
_ReaScripts-Templates/FX/Lokasenna_List params and values for focused FX.lua_

The output is for example:
```
Listing parameters for VST: ReaGate (Cockos)
	1 - Attack
		Real value: 0.0060000000521541
		Formatted: 3
	...
```
The attack for this FX is in _ms_. 

How can I retrieve the units of a FX parameter, or string of the value such as _3ms_?

**Comment by X-Raym** [comment]
@Erriez It is already displayed:

`Formatted: 3`

**Comment by Erriez** [comment]
@X-Raym I mean the unit in _ms_, not the value.

**Comment by X-Raym** [comment]
@Erriez It is not possible to get units names.

**Comment by Erriez** [comment]
@X-Raym Hmm, that confirms my finding. A little bit strange, because OSC sends FX parameter values as string which includes the unit information. So this is available inside Reaper, but cannot retrieved with the C/EEL/LUA/Python API's. 
Unfortunately, Reaper OSC is still not provided in source as I requested years ago, so I think there is no way to retrieve this info. 

I'll add a feature request on the Reaper developers forum. Thanks for your help!

**Comment by lossius** [comment]
I would recommend to look into OSCQuery Protocol: https://github.com/vidvox/oscqueryproposal

**Comment by Erriez** [comment]
@lossius Thanks, I'll have a look into this. 

In the mean time received an answer on the Reaper forum that units are included in the API call TrackFX_GetFormattedParamValue, but depends on the plugin:
https://forum.cockos.com/showthread.php?t=223498

**Comment by X-Raym** [comment]
@Erriez Yes indeed, but it is the same function which is already used int his script. Thats why I say it is not possible. If the plugin don't return units, then it can't be returned via API.
